### ISSUE TITLE
[Fight] Focus window lors du tour

### ISSUE THREAD

**Issue by Romain-P** [varKeytrap/Dofus.Retro.Supertools#1]

**Comment by keytrap-x86** [comment]
Salut, merci pour tes modifications. Tu peux faire un PR plutôt ? ça sera plus simple :)

**Comment by Romain-P** [comment]
Ah et si jamais tu n'étais pas au courant ils ont rajouté cloudflare sur les gameservers, donc tes ips ne sont plus valides. J'attends personnellement qu'un packet valide soit catch pour ensuite filtrer par ip (en me basant sur le premier packet qui a matché avec sa sourceIp)

**Comment by keytrap-x86** [comment]
> Désolé j'ai pas vraiment le temps, j'ai partagé juste l'idée si jamais tu trouvais ça intéressant :p 
> 
> Et j'ai trop de changements sur ma version ça me prendrait trop de temps :'(

Autant pour moi j'ai mal lu. J'avais pas compris que tu avais remodelé je croyais que tu voulais ajouter une modification.
Pour l'instant ce projet je n'y ai pas retouché et limite si je devais je l'aurais réécrit de à 0 pour qu'il soit plus propre et suive les principes SOLID.
Merci en tout cas. Et du coup toi en fais quoi toi?

**Comment by Romain-P** [comment]
> > Désolé j'ai pas vraiment le temps, j'ai partagé juste l'idée si jamais tu trouvais ça intéressant :p
> > Et j'ai trop de changements sur ma version ça me prendrait trop de temps :'(
> 
> Autant pour moi j'ai mal lu. J'avais pas compris que tu avais remodelé je croyais que tu voulais ajouter une modification. Pour l'instant ce projet je n'y ai pas retouché et limite si je devais je l'aurais réécrit de à 0 pour qu'il soit plus propre et suive les principes SOLID. Merci en tout cas. Et du coup toi en fais quoi toi?

Disons que c'est limite, je joue sur monocompte avec des VMs et j'ai adapté ton tool avec des VM pour multicompte assez facilement

**Comment by keytrap-x86** [comment]
Mdrrr j'en ai connu des forceurs mais j'aurai jamais pensé que des gens jouent via vm sur mono 😂

**Comment by Romain-P** [comment]
> Mdrrr j'en ai connu des forceurs mais j'aurai jamais pensé que des gens jouent via vm sur mono 😂

J'ai pas vraiment eu le temps d'investiguer tout ce qui a changé depuis la sortie de rétro aha, sinon j'aurais simplement MITM chaque process, mais dans le doute où il y a des traces sur le pc, j'ai préféré sandbox chaque dofus. Mieux vaut prévenir que guérir haha 

Si tu veux rigoler encore plus, j'ai setup 6 raspberry chez ma famille (1 par maison) pour avoir des VPN maison avec ip résidentielle, du coup chaque VM tourne avec une IP orange. Là tu peux parler de forcing hahaha

**Comment by Romain-P** [comment]
> Mdrrr j'en ai connu des forceurs mais j'aurai jamais pensé que des gens jouent via vm sur mono 😂

Sinon globalement j'ai pas du tout l'impression de jouer via une VM, VMware dispose d'un mode "Unity" qui réplique graphiquement avec les inputs/outputs chaque process de la VM.
En gros j'ai les dofus.exe sur mon host en dehors des VM, et pourtant chaque dofus.exe a sa propre IP et tourne bien dans une VM ^^

**Comment by keytrap-x86** [comment]
Très intéressant je vois que tu chômes pas. Je ne connaissais pas le Unity de VMWare ça a l'air bien pratique. Et oui la bonne idée des VPN comme ça plus de problème avec les IP. Content que mon tool t'a été utile :)
